Header header

#[WGS84 in degrees and heading in degrees]
#In navigation, bearing is the horizontal angle between the direction of an object and another object, or between it and that of true north.
#Absolute bearing refers to the angle between the magnetic North (magnetic bearing) or true North (true bearing) and an object. For example, an object to the East would have an absolute bearing of 90 degrees.
#Here the heading refers to the bearing concept.
geometry_msgs/Pose2D[] waypointList

#[m/s]
float64[] velocityList

float64[] curvatureList
