Header header

# Inertial reference system
float64 x
float64 y
float64 heading

# Vehicle Curvature [1/m]
float64 k

# Lane identification
int64 track_id
int8 lane_id

# Linear velocities [m/s]
float64 velocity
float64 longitudinal_velocity
float64 lateral_velocity

# Angular velocities
float64 angular_velocity

# Linear accelerations [m/s2]
float64 acceleration
float64 longitudal_acceleration
float64 lateral_acceleration

float64 s 

# Angular accelerations
