<?xml version="1.0"?>

<root xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- <xacro:include filename="$(find road_description)/urdf/materials.xacro" /> -->

  <!-- <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="panel_width"    value="0.07" />
  <xacro:property name="panel_depth"    value="0.07" />
  <xacro:property name="panel_height"   value="0.15" />
  <xacro:property name="tag_size"       value="0.05" />
  <xacro:property name="tag_z_offset"   value="0.065" />
  <xacro:property name="delta"          value="0.001" />
  <xacro:property name="light_width"    value="0.05" />
  <xacro:property name="light_height"   value="0.025" />
  <xacro:property name="light_z_offset" value="0.125" /> -->

  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="panel_width"    value="0.2" />
  <xacro:property name="panel_depth"    value="0.2" />
  <xacro:property name="panel_height"   value="0.3" />
  <xacro:property name="tag_size"       value="0.15" />
  <xacro:property name="tag_z_offset"   value="0.125" />
  <xacro:property name="delta"          value="0.002" />
  <xacro:property name="light_width"    value="0.1" />
  <xacro:property name="light_height"   value="0.05" />
  <xacro:property name="light_z_offset" value="0.250" />

  <xacro:macro name="landmark"
               params="name:=landmark
                       parent:=${name}_base_link
                       *origin
                       tag_dae1:=tag1
                       tag_dae2:=tag2
                       tag_dae3:=tag3
                       tag_dae4:=tag4
                                              ">

    <!-- tag_dae = tag95, tag47, tag74, tag29, tag57 -->
    <!-- light_color    = red,            green,            blue,           black -->
    <!-- light_material = Gazebo/RedGlow, Gazebo/GreenGlow, Gazebo/BlueSky, Gazebo/Black -->

    <!-- PANEL -->
    <joint name="joint_${parent}_to_${name}" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${panel_height/2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${panel_depth} ${panel_width} ${panel_height}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${panel_height/2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="${panel_depth} ${panel_width} ${panel_height}"/>
        </geometry>
      </collision>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="${name}_link">
      <material>Gazebo/White</material>
    </gazebo>
    <!-- PANEL -->

    <!-- TAG -->
    <joint name="joint_${name}_link_to_${name}_tag_link1" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_tag_link1"/>
    </joint>

    <link name="${name}_tag_link1">
    </link>

    <joint name="joint_${name}_tag_link_to_${name}_tag_image1" type="fixed">
      <origin xyz="${panel_depth/2.0+delta} 0 ${tag_size/2.0+tag_z_offset}" rpy="0 ${PI} -${PI/2}" />
      <parent link="${name}_tag_link1"/>
      <child link="${name}_tag_image1" />
    </joint>

    <link name="${name}_tag_image1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/trafficlight/dae/${tag_dae1}.dae" scale="${tag_size} 1.0 ${tag_size}"/>
        </geometry>
      </visual>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="${name}_tag_link1">
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${name}_tag_image1">
    </gazebo>
    <!-- TAG -->

    <!-- TAG2-->
    <joint name="joint_${name}_link_to_${name}_tag_link2" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_tag_link2"/>
    </joint>

    <link name="${name}_tag_link2">
    </link>

    <joint name="joint_${name}_tag_link2_to_${name}_tag_image2" type="fixed">
      <origin xyz="${-(panel_depth/2.0+delta)} 0 ${tag_size/2.0+tag_z_offset}" rpy="0 ${PI} ${PI/2}" />
      <parent link="${name}_tag_link2"/>
      <child link="${name}_tag_image2" />
    </joint>

    <link name="${name}_tag_image2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/trafficlight/dae/${tag_dae2}.dae" scale="${tag_size} 1.0 ${tag_size}"/>
        </geometry>
      </visual>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="${name}_tag_link2">
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${name}_tag_image2">
    </gazebo>
    <!-- TAG2 -->

    <!-- TAG3-->
    <joint name="joint_${name}_link_to_${name}_tag_link3" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_tag_link3"/>
    </joint>

    <link name="${name}_tag_link3">
    </link>

    <joint name="joint_${name}_tag_link3_to_${name}_tag_image3" type="fixed">
      <origin xyz="0 ${(panel_depth/2.0+delta)} ${tag_size/2.0+tag_z_offset}" rpy="0 ${PI} 0" />
      <parent link="${name}_tag_link3"/>
      <child link="${name}_tag_image3" />
    </joint>

    <link name="${name}_tag_image3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/trafficlight/dae/${tag_dae3}.dae" scale="${tag_size} 1.0 ${tag_size}"/>
        </geometry>
      </visual>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="${name}_tag_link3">
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${name}_tag_image3">
    </gazebo>
    <!-- TAG3 -->

    <!-- TAG4-->
    <joint name="joint_${name}_link_to_${name}_tag_link4" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_tag_link4"/>
    </joint>

    <link name="${name}_tag_link4">
    </link>

    <joint name="joint_${name}_tag_link4_to_${name}_tag_image4" type="fixed">
      <origin xyz="0 -${(panel_depth/2.0+delta)} ${tag_size/2.0+tag_z_offset}" rpy="0 ${PI} ${-PI}" />
      <parent link="${name}_tag_link4"/>
      <child link="${name}_tag_image4" />
    </joint>

    <link name="${name}_tag_image4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://road_description/urdf/trafficlight/dae/${tag_dae4}.dae" scale="${tag_size} 1.0 ${tag_size}"/>
        </geometry>
      </visual>
    </link>

    <gazebo>
      <static>1</static>
    </gazebo>

    <gazebo reference="${name}_tag_link4">
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="${name}_tag_image4">
    </gazebo>
    <!-- TAG4 -->

  </xacro:macro>

</root>
